/**
 * lib/supabase.ts
 *
 * Supabase client factory for the FMCG Field Sales CRM (Next.js App Router).
 * Uses @supabase/ssr to correctly handle cookies in all rendering contexts.
 *
 * Three exported helpers:
 *   createBrowserClient  → Client Components (browser)
 *   createServerClient   → Server Components, Server Actions, Route Handlers
 *   createAdminClient    → Server-only: bypasses RLS (service role key)
 *
 * Install deps:
 *   npm install @supabase/ssr @supabase/supabase-js
 */

// ─────────────────────────────────────────────────────────────────────────────
// Shared env-var assertions (fail fast at startup rather than at runtime)
// ─────────────────────────────────────────────────────────────────────────────
const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL;
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!SUPABASE_URL) {
  throw new Error(
    "Missing env var: NEXT_PUBLIC_SUPABASE_URL — add it to .env.local"
  );
}
if (!SUPABASE_ANON_KEY) {
  throw new Error(
    "Missing env var: NEXT_PUBLIC_SUPABASE_ANON_KEY — add it to .env.local"
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// 1. BROWSER CLIENT
//    Use inside Client Components ("use client").
//    Reads/writes cookies automatically through the browser's cookie jar.
//    Singleton pattern — @supabase/ssr is safe to call multiple times but
//    this keeps the reference stable across re-renders.
// ─────────────────────────────────────────────────────────────────────────────
import {
  createBrowserClient as _createBrowserClient,
  createServerClient as _createServerClient,
} from "@supabase/ssr";
import { createClient } from "@supabase/supabase-js";
import { cookies } from "next/headers";
import type { CookieOptions } from "@supabase/ssr";
import type { Database } from "@/types/database.types"; // generated by Supabase CLI (see below)

/**
 * Returns a Supabase client for use in Client Components.
 *
 * Usage:
 *   "use client"
 *   import { createBrowserClient } from "@/lib/supabase"
 *   const supabase = createBrowserClient()
 */
export function createBrowserClient() {
  return _createBrowserClient<Database>(
    SUPABASE_URL!,
    SUPABASE_ANON_KEY!
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// 2. SERVER CLIENT
//    Use inside Server Components, Server Actions, and Route Handlers.
//    Reads/writes cookies via next/headers — requires the Next.js request
//    context (i.e. cannot be called at module top-level or during build).
//
//    RLS is applied using the authenticated user's JWT from the cookie.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Returns a Supabase client for use in Server Components / Route Handlers.
 *
 * Usage (Server Component):
 *   import { createServerClient } from "@/lib/supabase"
 *   const supabase = await createServerClient()
 *   const { data } = await supabase.from("products").select()
 *
 * Usage (Server Action / Route Handler):
 *   import { createServerClient } from "@/lib/supabase"
 *   export async function POST(request: Request) {
 *     const supabase = await createServerClient()
 *     ...
 *   }
 */
export async function createServerClient() {
  const cookieStore = await cookies();

  return _createServerClient<Database>(
    SUPABASE_URL!,
    SUPABASE_ANON_KEY!,
    {
      cookies: {
        /**
         * Read all cookies from the Next.js cookie store.
         * Called by Supabase to retrieve the session JWT.
         */
        getAll() {
          return cookieStore.getAll();
        },

        /**
         * Write cookies back to the Next.js cookie store.
         * Called by Supabase when the session is refreshed.
         *
         * NOTE: In Server Components this is a no-op because the response
         * headers are already sent. Call this in a Server Action or Route
         * Handler where you control the response.
         */
        setAll(
          cookiesToSet: { name: string; value: string; options: CookieOptions }[]
        ) {
          try {
            cookiesToSet.forEach(({ name, value, options }) => {
              cookieStore.set(name, value, options);
            });
          } catch {
            // The `setAll` method can throw in Server Components.
            // Supabase middleware (see middleware.ts) handles token refresh
            // so this is safe to ignore here.
          }
        },
      },
    }
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// 3. ADMIN CLIENT (service role — BYPASSES RLS)
//    Use ONLY in trusted server-side code:
//      • Route Handlers that perform admin operations
//      • Supabase Edge Functions
//      • Background jobs / cron tasks
//    NEVER import this in a Client Component or expose to the browser.
// ─────────────────────────────────────────────────────────────────────────────
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_SERVICE_ROLE_KEY) {
  throw new Error(
    "Missing env var: SUPABASE_SERVICE_ROLE_KEY — add it to .env.local"
  );
}

/**
 * Returns a Supabase admin client that bypasses Row Level Security.
 *
 * Usage (Route Handler — server only):
 *   import { createAdminClient } from "@/lib/supabase"
 *   const supabaseAdmin = createAdminClient()
 *   const { data } = await supabaseAdmin.from("employees").select()
 */
export function createAdminClient() {
  return createClient<Database>(
    SUPABASE_URL!,
    SUPABASE_SERVICE_ROLE_KEY!,
    {
      auth: {
        // Disable auto-refresh & session persistence — this client is
        // server-side only and should never store a session in a cookie.
        autoRefreshToken: false,
        persistSession: false,
        detectSessionInUrl: false,
      },
    }
  );
}

// ─────────────────────────────────────────────────────────────────────────────
// NEXT STEPS
// ─────────────────────────────────────────────────────────────────────────────
// 1. Generate TypeScript types from your schema:
//      npx supabase gen types typescript --project-id <your-project-ref> \
//        --schema public > types/database.types.ts
//
// 2. Create middleware.ts at the project root to refresh sessions on every
//    request (required by @supabase/ssr):
//
//    import { createServerClient } from "@supabase/ssr"
//    import { NextResponse } from "next/server"
//    import type { NextRequest } from "next/server"
//
//    export async function middleware(request: NextRequest) {
//      let supabaseResponse = NextResponse.next({ request })
//      const supabase = createServerClient(
//        process.env.NEXT_PUBLIC_SUPABASE_URL!,
//        process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
//        {
//          cookies: {
//            getAll() { return request.cookies.getAll() },
//            setAll(cookiesToSet) {
//              cookiesToSet.forEach(({ name, value, options }) =>
//                supabaseResponse.cookies.set(name, value, options)
//              )
//            },
//          },
//        }
//      )
//      await supabase.auth.getUser()   // refreshes token if expired
//      return supabaseResponse
//    }
//
//    export const config = {
//      matcher: ["/((?!_next/static|_next/image|favicon.ico).*)"],
//    }
